<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>BLL_Business_Logic_Layer_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.21" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.32.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjektTaiib.DAL\ProjektTaiib.DAL.csproj" />
    <ProjectReference Include="..\ProjektTaiibWeb\ProjektTaiibWeb.csproj" />
  </ItemGroup>

</Project>
